import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The design system's central rule, enforced instead of merely stated.
///
/// `lib/core/design/tokens/dimensions.dart` opens by declaring that no literal
/// spacing, radius, size or duration may appear in a widget file, and
/// `docs/design_system.md` repeats it. Until this test existed the rule was
/// enforced by nothing but attention, and it had already drifted: four
/// different opacities for "tint a surface with an accent" and two hand-typed
/// copies of the same heading tracking, which is one edit away from two
/// different section headings.
///
/// The two values checked here are the ones that actually drifted. Both are
/// invisible in isolation and only wrong in aggregate, which is exactly the
/// class of mistake a reviewer does not catch and a test does.
void main() {
  final sources = Directory('lib')
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('.dart'))
      .where(_isWidgetFile)
      .toList();

  test('the sweep below finds widget files, rather than passing vacuously', () {
    // A path rename that quietly emptied this list would turn both checks into
    // no-ops that still report green — the worst possible failure mode for a
    // test whose entire job is to notice things.
    expect(sources.length, greaterThan(20));
  });

  test('durations come from AppDuration or AppDebounce, never inline', () {
    final offenders = _offenders(
      sources,
      RegExp(r'Duration\(\s*(milliseconds|seconds):'),
    );

    expect(
      offenders,
      isEmpty,
      reason:
          'An inline Duration is a timing decision made inside one widget, '
          'where the next widget cannot see it. Add a token to '
          'lib/core/design/tokens/motion.dart instead:\n${offenders.join('\n')}',
    );
  });

  test('surface opacities come from AppTint, never inline', () {
    final offenders = _offenders(
      sources,
      // `alpha: 0` — fully transparent — is the end of a gradient rather than
      // a tint strength, and there is nothing to name.
      RegExp(r'alpha:\s*0\.\d'),
    );

    expect(
      offenders,
      isEmpty,
      reason:
          'Tint strengths must be shared or they diverge, and a stronger tint '
          'reads as meaning more. Add a token to '
          'lib/core/design/tokens/colors.dart instead:\n${offenders.join('\n')}',
    );
  });
}

/// Whether the rule applies to this file.
///
/// The rule is about *widget* files, and scoping it that way is not a loophole
/// — it is the difference between a design system and a style guide for the
/// whole program. `lib/core/api/` holds connect and receive timeouts and a
/// retry backoff: real durations, correctly named at the top of their own
/// files, and none of them motion. Pulling them into
/// `lib/core/design/tokens/motion.dart` would put HTTP timings in the design
/// system and teach the next person that the token files are where unrelated
/// numbers go to be legal.
bool _isWidgetFile(File file) {
  final path = file.path;

  // Generated by `flutter gen-l10n`, rewritten wholesale on regeneration.
  if (path.contains('/l10n/')) return false;

  // Where these values are *defined*. Excluding them is the point: the rule is
  // "declare it once", not "never write a number".
  if (path.startsWith('lib/core/design/tokens')) return false;

  return path.startsWith('lib/core/design') ||
      path.startsWith('lib/core/navigation') ||
      path.contains('/presentation/');
}

/// Every `path:line` where [pattern] appears, so a failure names the file to
/// open rather than only the rule that was broken.
List<String> _offenders(List<File> sources, RegExp pattern) {
  final found = <String>[];

  for (final file in sources) {
    final lines = file.readAsLinesSync();
    for (final (index, line) in lines.indexed) {
      // Skip prose: doc comments quote these values when explaining them.
      final code = line.trimLeft();
      if (code.startsWith('//') || code.startsWith('///')) continue;
      if (pattern.hasMatch(line)) {
        found.add('  ${file.path}:${index + 1}  ${code.trim()}');
      }
    }
  }

  return found;
}
